In [1]:
import tensorflow as tf
import numpy as np

In [2]:
m1 = tf.constant(np.array([i for i in range(1,10)]).reshape(3,3))
m2 = tf.constant(np.array([i for i in range(91,100)]).reshape(3,3))

In [3]:
sum_mat = m1 + m2

In [4]:
with tf.Session() as sess:
    print(sess.run(sum_mat))

[[ 92  94  96]
 [ 98 100 102]
 [104 106 108]]


In [5]:
tf.reset_default_graph()

v1 = tf.constant(np.array([i for i in range(1,10)]))
v2 = tf.constant(np.array([i for i in range(91,100)]))
               

with tf.Session() as sess:
    print(sess.run(tf.add(v1, v2 )))
    print()
    print(sess.run(tf.add(v1, v2 )).reshape(3,3))

[ 92  94  96  98 100 102 104 106 108]

[[ 92  94  96]
 [ 98 100 102]
 [104 106 108]]
