In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# using np

mat1 = np.array([i for i in range(1,5)]).reshape(2, 2)
mat2 = np.array([i for i in range(66, 70)]).reshape(2, 2)

print(mat1)
print('\n', mat2, '\n')

print(np.matmul(mat1, mat2))

[[1 2]
 [3 4]]

 [[66 67]
 [68 69]] 

[[202 205]
 [470 477]]


In [3]:
m1 = tf.constant(np.array([i for i in range(1,5)]).reshape(2, 2), dtype='int32')
m2 = tf.constant(np.array([i for i in range(66, 70)]).reshape(2, 2), dtype='int32')

with tf.Session() as sess:
    print(sess.run(tf.matmul(m1, m2)))

[[202 205]
 [470 477]]
