In [1]:
import numpy as np

# Basic Operations

In [2]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
np.array([1,2,3,4], dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [9]:
np.linspace(start=1, stop=10, num=10).reshape(2,5)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [10]:
b = np.arange(12).reshape(3,4)
print(b)
print("Sum each column")
b.sum(axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Sum each column


array([12, 15, 18, 21])

print("Sum each line")
print(b)
b.sum(axis=1).reshape(3,1)

# Universal Functions

In [11]:
arr = np.array([4, 9, 16, 25])
np.exp(arr)

array([5.45981500e+01, 8.10308393e+03, 8.88611052e+06, 7.20048993e+10])

In [12]:
np.sqrt(arr)

array([2., 3., 4., 5.])

In [13]:
np.add(arr, [-4, 1, -1, -5])

array([ 0, 10, 15, 20])

In [14]:
# Equal line above
arr + [-4, 1, -1, -5]

array([ 0, 10, 15, 20])

# Slicing

In [15]:
print(arr)
arr[1]

[ 4  9 16 25]


9

In [16]:
arr[2:]

array([16, 25])

In [17]:
arr2d = np.arange(1,10).reshape(3, 3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Iterating

In [18]:
for row in arr2d:
    print(row)
    print('------')

[1 2 3]
------
[4 5 6]
------
[7 8 9]
------


In [19]:
# Get all elements from the array
for element in arr2d.flat:
    print(element)

1
2
3
4
5
6
7
8
9


In [20]:
# same as above, but it keeps being a np.array
arr2d = arr2d.ravel()
arr2d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# It changes the struct internally
arr2d.resize(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# It doesn't change the struct internally
print(arr2d.reshape(9,1))
arr2d

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Stacking together different arrays

In [23]:
a = np.floor(10*np.random.random((2,2)))
a

array([[4., 4.],
       [9., 7.]])

In [24]:
b = np.floor(10*np.random.random((2,2)))
b

array([[0., 9.],
       [6., 1.]])

In [25]:
np.vstack((a,b))

array([[4., 4.],
       [9., 7.],
       [0., 9.],
       [6., 1.]])

In [26]:
# Is the same as above
np.concatenate((a,b))

array([[4., 4.],
       [9., 7.],
       [0., 9.],
       [6., 1.]])

In [27]:
np.hstack((a,b))

array([[4., 4., 0., 9.],
       [9., 7., 6., 1.]])

In [28]:
# Is the same as above
np.concatenate((a,b), axis=1)

array([[4., 4., 0., 9.],
       [9., 7., 6., 1.]])

In [29]:
arr_transpose = np.concatenate((a,b), axis=1)
print(np.transpose(arr_transpose))
arr_transpose.T

[[4. 9.]
 [4. 7.]
 [0. 6.]
 [9. 1.]]


array([[4., 9.],
       [4., 7.],
       [0., 6.],
       [9., 1.]])

# Statistics

In [30]:
arr = np.arange(1,10)
print(arr)
arr.mean()

[1 2 3 4 5 6 7 8 9]


5.0

In [31]:
arr.std()

2.581988897471611

In [32]:
arr.var()

6.666666666666667

# Basic Linear Algebra

In [33]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [34]:
b = np.array([[1,2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [35]:
a * b

array([[ 1,  4],
       [ 9, 16]])

In [36]:
np.dot(a,b) # multiply line vs column

array([[ 7, 10],
       [15, 22]])